apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-deploy
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  metadata:
    labels:
      app: frontend
  spec:
    containers:
      - name: amazon-container
        image: amazon-img
        ports:
          - name: frontend-port
            containerPort: 80
            protocol: TCP
